project_id = "ktzixrajviveolgggilq"

[functions.secure-notifications]
verify_jwt = true

[functions.telegram-webhook]
verify_jwt = false

[functions.ai-recommendations] 
verify_jwt = true

[functions.project-analytics]
verify_jwt = true

[functions.export-reports]
verify_jwt = true

[functions.ai-provider-test]
verify_jwt = true

[functions.ai-monitoring]
verify_jwt = false